{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "soc-autopilot.serviceAccountName" . }}
  labels:
    {{- include "soc-autopilot.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
